{% set name = "sensormapgeo" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sensormapgeo-{{ version }}.tar.gz
  sha256: 90a1957e2871a6645a050ccea0a40fe0c57bfabc67a67c9eb47ed6c25c0e8e23

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - gdal
    - numpy
    - _openmp_mutex =* =*_llvm  # [linux]
    - pebble
    - py-tools-ds >=0.14.26
    - pyproj >=2.2
    - pyresample >=1.11.0
    - python

test:
  imports:
    - sensormapgeo
    - sensormapgeo.transformer_2d
    - sensormapgeo.transformer_3d
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitext.gfz-potsdam.de/EnMAP/sensormapgeo
  summary: A package for transforming remote sensing images between sensor and map geometry.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
