{% set name = "sensormapgeo" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sensormapgeo-{{ version }}.tar.gz
  sha256: 02af87c909f24bd0a78fe0b2a3d25c1b8c935b97b3e3b2e64367b2d1c51a6e2e

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - gdal >=3.8
    - joblib
    - numpy
    - py-tools-ds >=0.18.0
    - pyproj >=2.2
    - pyresample >=1.17.0
    - python

test:
  imports:
    - sensormapgeo
    - sensormapgeo.transformer
    - sensormapgeo.gdal_backend.transformer_2d
    - sensormapgeo.gdal_backend.transformer_3d
    - sensormapgeo.pyresample_backend.transformer_2d
    - sensormapgeo.pyresample_backend.transformer_3d
    - sensormapgeo.transformer_2d
    - sensormapgeo.transformer_3d
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/sensormapgeo
  summary: A package for transforming remote sensing images between sensor and map geometry.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
