{% set name = "sensormapgeo" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sensormapgeo-{{ version }}.tar.gz
  sha256: 259b2657acb16b996ca46b4fc4755062e9e1b0ab2be12b1bef1b9b3994b164fb

build:
  number: 2
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - fontconfig >=2.13.1,<2.13.96  # [osx and py==37]  # intermediate fix for https://github.com/kb47/pdf-poppler/issues/2#issuecomment-1063521221
    - gdal
    - numpy
    - _openmp_mutex =* =*_llvm  # [linux]
    - pebble
    - py-tools-ds >=0.18.0
    - pyproj >=2.2
    - pyresample >=1.17.0
    - python

test:
  imports:
    - sensormapgeo
    - sensormapgeo.transformer_2d
    - sensormapgeo.transformer_3d
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/sensormapgeo
  summary: A package for transforming remote sensing images between sensor and map geometry.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
